namespace BudgetWarden_Windows.ViewModels;

internal static class CurrencyCatalog
{
    public static IReadOnlyList<CurrencyOption> All { get; } =
    [
        Currency("AED", "UAE Dirham"),
        Currency("AFN", "Afghan Afghani", "؋"),
        Currency("ALL", "Albanian Lek"),
        Currency("AMD", "Armenian Dram", "֏"),
        Currency("ANG", "Netherlands Antillean Guilder"),
        Currency("AOA", "Angolan Kwanza", "Kz"),
        Currency("ARS", "Argentine Peso"),
        Currency("AUD", "Australian Dollar", "A$"),
        Currency("AWG", "Aruban Florin"),
        Currency("AZN", "Azerbaijani Manat", "₼"),
        Currency("BAM", "Bosnia and Herzegovina Convertible Mark", "KM"),
        Currency("BBD", "Barbados Dollar"),
        Currency("BDT", "Bangladeshi Taka", "৳"),
        Currency("BGN", "Bulgarian Lev", "лв"),
        Currency("BHD", "Bahraini Dinar"),
        Currency("BIF", "Burundian Franc"),
        Currency("BMD", "Bermudian Dollar"),
        Currency("BND", "Brunei Dollar"),
        Currency("BOB", "Boliviano", "Bs."),
        Currency("BRL", "Brazilian Real", "R$"),
        Currency("BSD", "Bahamian Dollar"),
        Currency("BTN", "Bhutanese Ngultrum", "Nu."),
        Currency("BWP", "Botswana Pula", "P"),
        Currency("BYN", "Belarusian Ruble", "Br"),
        Currency("BZD", "Belize Dollar"),
        Currency("CAD", "Canadian Dollar", "CA$"),
        Currency("CDF", "Congolese Franc"),
        Currency("CHF", "Swiss Franc"),
        Currency("CLP", "Chilean Peso"),
        Currency("CNY", "Chinese Yuan", "CN¥"),
        Currency("COP", "Colombian Peso"),
        Currency("CRC", "Costa Rican Colón", "₡"),
        Currency("CUP", "Cuban Peso"),
        Currency("CVE", "Cabo Verde Escudo"),
        Currency("CZK", "Czech Koruna", "Kč"),
        Currency("DJF", "Djibouti Franc"),
        Currency("DKK", "Danish Krone", "kr"),
        Currency("DOP", "Dominican Peso"),
        Currency("DZD", "Algerian Dinar"),
        Currency("EGP", "Egyptian Pound"),
        Currency("ERN", "Eritrean Nakfa", "Nfk"),
        Currency("ETB", "Ethiopian Birr", "Br"),
        Currency("EUR", "Euro", "€"),
        Currency("FJD", "Fiji Dollar"),
        Currency("FKP", "Falkland Islands Pound"),
        Currency("GBP", "Pound Sterling", "£"),
        Currency("GEL", "Georgian Lari", "₾"),
        Currency("GHS", "Ghana Cedi", "GH₵"),
        Currency("GIP", "Gibraltar Pound"),
        Currency("GMD", "Gambian Dalasi", "D"),
        Currency("GNF", "Guinean Franc"),
        Currency("GTQ", "Guatemalan Quetzal", "Q"),
        Currency("GYD", "Guyana Dollar"),
        Currency("HKD", "Hong Kong Dollar", "HK$"),
        Currency("HNL", "Honduran Lempira", "L"),
        Currency("HTG", "Haitian Gourde", "G"),
        Currency("HUF", "Hungarian Forint", "Ft"),
        Currency("IDR", "Indonesian Rupiah", "Rp"),
        Currency("ILS", "Israeli New Shekel", "₪"),
        Currency("INR", "Indian Rupee", "₹"),
        Currency("IQD", "Iraqi Dinar"),
        Currency("IRR", "Iranian Rial"),
        Currency("ISK", "Icelandic Króna", "kr"),
        Currency("JMD", "Jamaican Dollar", "J$"),
        Currency("JOD", "Jordanian Dinar"),
        Currency("JPY", "Japanese Yen", "¥"),
        Currency("KES", "Kenyan Shilling", "KSh"),
        Currency("KGS", "Kyrgyzstani Som"),
        Currency("KHR", "Cambodian Riel", "៛"),
        Currency("KMF", "Comorian Franc"),
        Currency("KPW", "North Korean Won", "₩"),
        Currency("KRW", "South Korean Won", "₩"),
        Currency("KWD", "Kuwaiti Dinar"),
        Currency("KYD", "Cayman Islands Dollar"),
        Currency("KZT", "Kazakhstani Tenge", "₸"),
        Currency("LAK", "Lao Kip", "₭"),
        Currency("LBP", "Lebanese Pound"),
        Currency("LKR", "Sri Lanka Rupee", "Rs"),
        Currency("LRD", "Liberian Dollar"),
        Currency("LSL", "Lesotho Loti", "L"),
        Currency("LYD", "Libyan Dinar"),
        Currency("MAD", "Moroccan Dirham"),
        Currency("MDL", "Moldovan Leu", "L"),
        Currency("MGA", "Malagasy Ariary", "Ar"),
        Currency("MKD", "Denar", "ден"),
        Currency("MMK", "Myanmar Kyat", "K"),
        Currency("MNT", "Mongolian Tögrög", "₮"),
        Currency("MOP", "Macanese Pataca", "MOP$"),
        Currency("MRU", "Mauritanian Ouguiya", "UM"),
        Currency("MUR", "Mauritius Rupee"),
        Currency("MVR", "Maldivian Rufiyaa", "Rf"),
        Currency("MWK", "Malawian Kwacha", "MK"),
        Currency("MXN", "Mexican Peso", "MX$"),
        Currency("MYR", "Malaysian Ringgit", "RM"),
        Currency("MZN", "Mozambique Metical", "MT"),
        Currency("NAD", "Namibia Dollar", "N$"),
        Currency("NGN", "Nigerian Naira", "₦"),
        Currency("NIO", "Nicaraguan Córdoba", "C$"),
        Currency("NOK", "Norwegian Krone", "kr"),
        Currency("NPR", "Nepalese Rupee"),
        Currency("NZD", "New Zealand Dollar", "NZ$"),
        Currency("OMR", "Omani Rial"),
        Currency("PAB", "Panamanian Balboa", "B/."),
        Currency("PEN", "Peruvian Sol", "S/"),
        Currency("PGK", "Papua New Guinean Kina", "K"),
        Currency("PHP", "Philippine Peso", "₱"),
        Currency("PKR", "Pakistan Rupee"),
        Currency("PLN", "Polish Złoty", "zł"),
        Currency("PYG", "Paraguayan Guaraní", "₲"),
        Currency("QAR", "Qatari Rial"),
        Currency("RON", "Romanian Leu", "lei"),
        Currency("RSD", "Serbian Dinar", "din."),
        Currency("RUB", "Russian Ruble", "₽"),
        Currency("RWF", "Rwandan Franc"),
        Currency("SAR", "Saudi Riyal"),
        Currency("SBD", "Solomon Islands Dollar"),
        Currency("SCR", "Seychelles Rupee"),
        Currency("SDG", "Sudanese Pound"),
        Currency("SEK", "Swedish Krona", "kr"),
        Currency("SGD", "Singapore Dollar", "S$"),
        Currency("SHP", "Saint Helena Pound"),
        Currency("SLE", "Sierra Leonean Leone", "Le"),
        Currency("SLL", "Sierra Leonean Leone (legacy)", "Le"),
        Currency("SOS", "Somali Shilling"),
        Currency("SRD", "Surinam Dollar"),
        Currency("SSP", "South Sudanese Pound"),
        Currency("STN", "São Tomé and Príncipe Dobra", "Db"),
        Currency("SVC", "El Salvador Colón", "₡"),
        Currency("SYP", "Syrian Pound"),
        Currency("SZL", "Eswatini Lilangeni", "L"),
        Currency("THB", "Thai Baht", "฿"),
        Currency("TJS", "Tajikistani Somoni", "SM"),
        Currency("TMT", "Turkmenistan New Manat", "m"),
        Currency("TND", "Tunisian Dinar"),
        Currency("TOP", "Tongan Paʻanga", "T$"),
        Currency("TRY", "Turkish Lira", "₺"),
        Currency("TTD", "Trinidad and Tobago Dollar", "TT$"),
        Currency("TWD", "New Taiwan Dollar", "NT$"),
        Currency("TZS", "Tanzanian Shilling", "TSh"),
        Currency("UAH", "Ukrainian Hryvnia", "₴"),
        Currency("UGX", "Uganda Shilling", "USh"),
        Currency("USD", "US Dollar", "$"),
        Currency("UYU", "Peso Uruguayo", "$U"),
        Currency("UZS", "Uzbekistan Sum"),
        Currency("VED", "Venezuelan Bolívar Digital", "Bs."),
        Currency("VES", "Venezuelan Bolívar Soberano", "Bs."),
        Currency("VND", "Vietnamese Đồng", "₫"),
        Currency("VUV", "Vanuatu Vatu", "VT"),
        Currency("WST", "Samoan Tala", "WS$"),
        Currency("XAF", "CFA Franc BEAC", "FCFA"),
        Currency("XCD", "East Caribbean Dollar", "EC$"),
        Currency("XCG", "Caribbean Guilder", "Cg."),
        Currency("XOF", "CFA Franc BCEAO", "CFA"),
        Currency("XPF", "CFP Franc", "CFPF"),
        Currency("YER", "Yemeni Rial"),
        Currency("ZAR", "South African Rand", "R"),
        Currency("ZMW", "Zambian Kwacha", "ZK"),
        Currency("ZWG", "Zimbabwe Gold", "ZiG"),
        Currency("ZWL", "Zimbabwe Dollar (legacy)", "Z$"),
    ];

    private static CurrencyOption Currency(string code, string name, string? symbol = null) =>
        new(code, name, symbol ?? code);
}
