using Bw_core;
using CoreApi = Bw_core.Bw_core;

static void Require(bool condition, string message)
{
    if (!condition) throw new InvalidOperationException(message);
}

CoreApi.InitializeCore(Guid.NewGuid());
BwBudget budget = CoreApi.BudgetFromTemplate(BwTemplateType.BasicMonthly, "Windows Core Smoke");
Require(budget.Categories.Length == 13, "The monthly template did not return 13 categories.");
Require(budget.Changes.Categories.Count == 13, "The generated C# binding lost category CRDT changes.");
Require(budget.OrderedCategories(null).Length == 13, "Core category ordering failed.");

BwReportingSummary initialReport = CoreApi.BuildReportingSummary(budget);
Require(initialReport.CategorySegments.Length == 13, "Core reporting did not return every category.");

string encoded = CoreApi.EncodeBudget(budget);
BwBudget decoded = CoreApi.DecodeBudget(encoded, "C:\\WindowsCoreSmoke.budget");
Require(decoded.Categories.Length == 13, "Core JSON round-trip lost categories.");
Require(decoded.Changes.Categories.Count == 13, "Core JSON round-trip lost CRDT changes.");

BwCategory salary = decoded.Categories.First(category => category.CategoryType == BwCategoryType.Income);
BwTransaction transaction = CoreApi.NewTransaction(
    "Smoke paycheck",
    "Generated by the Windows core smoke test",
    new BwDate(2026, 7, 25),
    new BwMoneyAmount(100_00));
BwBudget mutated = CoreApi.CreateTransaction(decoded, salary.Id, transaction).UpdateActuals();
BwCategory updatedSalary = mutated.Categories.First(category => category.Id == salary.Id);
Require(updatedSalary.AmountActual.Value == 100_00, "Core transaction mutation did not update actuals.");
CoreApi.ValidateBudget(mutated);

if (args is ["--output", string outputPath])
{
    string normalized = Path.GetFullPath(outputPath);
    Directory.CreateDirectory(Path.GetDirectoryName(normalized)!);
    File.WriteAllText(normalized, CoreApi.EncodeBudget(mutated with { Url = normalized }));
    Console.WriteLine($"Wrote {normalized}");
}

Console.WriteLine("CORE_SMOKE_OK");
